// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignment/consignment.proto

package go_micro_srv_consignment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_7963c5b8b82ff2e6, []int{0}
}
func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (dst *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(dst, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_7963c5b8b82ff2e6, []int{1}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Response struct {
	Created              bool           `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment   `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	Consigments          []*Consignment `protobuf:"bytes,3,rep,name=consigments,proto3" json:"consigments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_7963c5b8b82ff2e6, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func (m *Response) GetConsigments() []*Consignment {
	if m != nil {
		return m.Consigments
	}
	return nil
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_7963c5b8b82ff2e6, []int{3}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Consignment)(nil), "go.micro.srv.consignment.Consignment")
	proto.RegisterType((*Container)(nil), "go.micro.srv.consignment.Container")
	proto.RegisterType((*Response)(nil), "go.micro.srv.consignment.Response")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.consignment.GetRequest")
}

func init() {
	proto.RegisterFile("proto/consignment/consignment.proto", fileDescriptor_consignment_7963c5b8b82ff2e6)
}

var fileDescriptor_consignment_7963c5b8b82ff2e6 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4e, 0xf3, 0x30,
	0x10, 0xfd, 0xd2, 0xff, 0x4c, 0x3e, 0x7d, 0x9f, 0xea, 0x05, 0x58, 0xb0, 0x20, 0x4a, 0x41, 0xea,
	0x2a, 0x48, 0xe5, 0x04, 0x28, 0x8b, 0xaa, 0x5b, 0xf7, 0x00, 0xa5, 0xc4, 0xa3, 0xd4, 0x52, 0x63,
	0x07, 0xdb, 0x2d, 0x37, 0x43, 0xe2, 0x1e, 0x1c, 0x08, 0xc5, 0x69, 0xa8, 0x25, 0x54, 0x54, 0x76,
	0x7e, 0xf3, 0xfc, 0xe6, 0xbd, 0x19, 0x0d, 0x4c, 0x2a, 0xad, 0xac, 0xba, 0xcf, 0x95, 0x34, 0xa2,
	0x90, 0x25, 0x4a, 0xeb, 0xbf, 0x53, 0xc7, 0x12, 0x5a, 0xa8, 0xb4, 0x14, 0xb9, 0x56, 0xa9, 0xd1,
	0xfb, 0xd4, 0xe3, 0x93, 0xf7, 0x00, 0xa2, 0xec, 0x88, 0xc9, 0x3f, 0xe8, 0x08, 0x4e, 0x83, 0x38,
	0x98, 0x86, 0xac, 0x23, 0x38, 0x89, 0x21, 0xe2, 0x68, 0x72, 0x2d, 0x2a, 0x2b, 0x94, 0xa4, 0x1d,
	0x47, 0xf8, 0x25, 0x72, 0x01, 0x83, 0x57, 0x14, 0xc5, 0xc6, 0xd2, 0x6e, 0x1c, 0x4c, 0xfb, 0xec,
	0x80, 0x48, 0x06, 0x90, 0x2b, 0x69, 0xd7, 0x42, 0xa2, 0x36, 0xb4, 0x17, 0x77, 0xa7, 0xd1, 0x6c,
	0x92, 0x9e, 0x0a, 0x92, 0x66, 0xed, 0x5f, 0xe6, 0xc9, 0xc8, 0x35, 0x84, 0x7b, 0x34, 0x06, 0xb7,
	0x2b, 0xc1, 0x69, 0xdf, 0x99, 0x8f, 0x9a, 0xc2, 0x82, 0x27, 0x25, 0x84, 0x5f, 0xaa, 0x6f, 0xc1,
	0x6f, 0x20, 0xca, 0x77, 0xc6, 0xaa, 0x12, 0x75, 0xad, 0x6d, 0x82, 0x43, 0x5b, 0x5a, 0xf0, 0x3a,
	0xb7, 0xd2, 0xa2, 0x10, 0xd2, 0xe5, 0x0e, 0xd9, 0x01, 0x91, 0x4b, 0x18, 0xee, 0x4c, 0x23, 0xea,
	0x35, 0x44, 0x0d, 0x17, 0x3c, 0x79, 0x0b, 0x60, 0xc4, 0xd0, 0x54, 0x4a, 0x1a, 0x24, 0x14, 0x86,
	0xb9, 0xc6, 0xb5, 0xc5, 0xc6, 0x73, 0xc4, 0x5a, 0x48, 0xe6, 0x10, 0x79, 0x73, 0x39, 0xe3, 0x68,
	0x76, 0xf7, 0xe3, 0xe0, 0xed, 0x9b, 0xf9, 0xca, 0x63, 0xa3, 0x1a, 0x19, 0xda, 0x75, 0x1b, 0xfc,
	0x5d, 0x23, 0xa7, 0x4c, 0xfe, 0x02, 0xcc, 0xd1, 0x32, 0x7c, 0xd9, 0xa1, 0xb1, 0xb3, 0x8f, 0x00,
	0xfe, 0x2f, 0x37, 0xa2, 0xaa, 0x84, 0x2c, 0x96, 0xa8, 0xf7, 0x22, 0x47, 0xf2, 0x04, 0xe3, 0xcc,
	0xc5, 0xf7, 0x4f, 0xe1, 0x3c, 0xab, 0xab, 0xe4, 0xf4, 0xb7, 0x76, 0x5b, 0xc9, 0x1f, 0xb2, 0x82,
	0xf1, 0x1c, 0xed, 0xe3, 0x76, 0xeb, 0x3b, 0xdc, 0x9e, 0x96, 0x1e, 0x03, 0x9f, 0x67, 0xf0, 0x3c,
	0x70, 0x97, 0xfe, 0xf0, 0x19, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xaa, 0xdc, 0xbd, 0x10, 0x03, 0x00,
	0x00,
}
